const nodemailer = require('nodemailer');

// Mock transporter if no configs
const transporter = process.env.EMAIL_USER ? nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
    }
}) : null;

exports.sendNotification = async (report, analysis) => {
    const isCritical = analysis.severityScore >= 8;
    const isHigh = analysis.severityScore >= 6;

    if (!isCritical && !isHigh) {
        return; // No notification needed for low priority
    }

    const subject = `${analysis.threatLevel.toUpperCase()} ALERT: ${report.title}`;
    const html = `
        <h2>Civic Issue Alert</h2>
        <p><strong>Threat Level:</strong> ${analysis.threatLevel}</p>
        <p><strong>Severity:</strong> ${analysis.severityScore}/10</p>
        <p><strong>Location:</strong> ${report.location}</p>
        <p><strong>Description:</strong> ${report.description}</p>
        <br>
        <p><em>Auto-generated by CivicSense AI</em></p>
    `;

    console.log(`\n [NOTIFICATION TRIGGERED]`);
    console.log(`To: Authorities`);
    console.log(`Subject: ${subject}`);
    console.log(`Threat: ${analysis.threatLevel}`);
    console.log(`----------------------------------\n`);

    if (transporter && process.env.ALERT_EMAIL) {
        try {
            await transporter.sendMail({
                from: process.env.EMAIL_USER,
                to: process.env.ALERT_EMAIL,
                subject,
                html
            });
            console.log('✅ Email sent successfully');
        } catch (error) {
            console.error('❌ Failed to send email:', error);
        }
    } else {
        console.log('ℹ️ Email credentials not found. simulating email send.');
    }
};

exports.sendOTP = async (email, otp) => {
    const subject = `Your CivicSense Verification Code: ${otp}`;
    const html = `
        <div style="font-family: sans-serif; padding: 20px; border: 1px solid #eee;">
            <h2>Verify your Account</h2>
            <p>Thank you for joining CivicSense. Use the following code to verify your identity:</p>
            <h1 style="color: #1e3a8a; letter-spacing: 5px;">${otp}</h1>
            <p>This code will expire in 10 minutes.</p>
        </div>
    `;

    console.log(`\n📧 [OTP SENT] To: ${email} | Code: ${otp} 📧\n`);

    if (transporter) {
        try {
            await transporter.sendMail({
                from: process.env.EMAIL_USER,
                to: email,
                subject,
                html
            });
        } catch (error) {
            console.error('❌ Failed to send OTP email:', error);
        }
    }
};

